name: Summarize Work Activity
description: Summarize your activity on github and add it to your repo's ReadME
author: Ahmed33033

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: heart
  color: red

inputs:
  prompt:
    required: true
    description: the prompt for the AI model

# Define your outputs here.
outputs:
  response:
    description: The AI Agent's response

runs:
  using: node24
  main: dist/index.js
